# Stacks detected: deps:node:.,test:jest:
version: 2.1
orbs:
  node: circleci/node@5
  aws-ecr: circleci/aws-ecr@9.0.2
jobs:
  test:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm test -- --coverage --forceExit
      - store_test_results:
          path: ./test-results/
  build-deploy:
    # building image
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build . -t devsu-nodedemo:$TAG
workflows:
  build-and-test:
    jobs:
      - test
      - build-deploy:
          requires:
            - test
