# Stacks detected: deps:node:.,test:jest:
version: 2.1
orbs:
  node: circleci/node@5
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  test:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm test -- --coverage --forceExit
      - store_test_results:
          path: ./test-results/
  build-push:
    # building image
    executor: aws-cli/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build_and_push_image:
          account_id: $AWS_ID
          auth:
            - aws-cli/setup:
                profile_name: OIDC-PROFILE
                role_arn: $ARN_ROLE
                region: $REGION
          create_repo: true
          profile_name: OIDC-PROFILE
          public_registry: false
          push_image: true
          region: $REGION
          repo: $REPOSITORY
          tag: $TAG
workflows:
  build-and-test:
    jobs:
      - test
      - build-push:
          context: aws
          requires:
            - test
          
