replicaCount: 2

image:
  repository: 851725212434.dkr.ecr.us-east-1.amazonaws.com/devsudemo
  pullPolicy: IfNotPresent
  tag: "latest"

labels:
  env: "dev"

service:
  port: 8000
  targetPort: 8000
  type: LoadBalancer

replicaCount: 1

autoscaling:
  enabled: false

ingress:
  enabled: false

imagePullSecrets:
  - name: regcred